---
- name: check vsphere_username value
  fail:
    msg: "vsphere_username is missing"
  when: vsphere_username is not defined or vsphere_username == ""

- name: check vsphere_password value
  fail:
    msg: "vsphere_password is missing"
  when: vsphere_password is not defined or vsphere_password == ""

- name: check vsphere_server value
  fail:
    msg: "vsphere_server is missing"
  when: vsphere_server is not defined or vsphere_server == ""

- name: check vsphere_datacenter value
  fail:
    msg: "vsphere_datacenter is missing"
  when: vsphere_datacenter is not defined or vsphere_datacenter == ""

- name: check vsphere_datastore value
  fail:
    msg: "vsphere_datastore is missing"
  when: vsphere_datastore is not defined or vsphere_datastore == ""

- name: check vsphere_working_dir value
  fail:
    msg: "vsphere_working_dir is missing"
  when: vsphere_working_dir is not defined or vsphere_working_dir == ""
